import {
  pgTable,
  uuid,
  varchar,
  text,
  integer,
  decimal,
  date,
  timestamp,
  boolean,
} from 'drizzle-orm/pg-core';

export const hostels = pgTable('hostels', {
  id: uuid('id').primaryKey().defaultRandom(),
  tenantId: uuid('tenant_id').notNull(),
  branchId: uuid('branch_id').notNull(),
  name: varchar('name', { length: 200 }).notNull(),
  code: varchar('code', { length: 50 }),
  address: text('address'),
  wardenId: uuid('warden_id'),
  totalRooms: integer('total_rooms').default(0),
  totalBeds: integer('total_beds').default(0),
  isActive: boolean('is_active').default(true),
  status: varchar('status', { length: 20 }).default('active'),
  notes: text('notes'),
  createdAt: timestamp('created_at').defaultNow(),
  updatedAt: timestamp('updated_at').defaultNow(),
  deletedAt: timestamp('deleted_at'),
});

export const hostelRooms = pgTable('hostel_rooms', {
  id: uuid('id').primaryKey().defaultRandom(),
  hostelId: uuid('hostel_id').notNull(),
  roomNumber: varchar('room_number', { length: 20 }).notNull(),
  floor: integer('floor'),
  capacity: integer('capacity').default(1),
  bedCount: integer('bed_count').default(1),
  roomType: varchar('room_type', { length: 50 }),
  rentAmount: decimal('rent_amount', { precision: 10, scale: 2 }),
  isActive: boolean('is_active').default(true),
  status: varchar('status', { length: 20 }).default('available'),
  notes: text('notes'),
  createdAt: timestamp('created_at').defaultNow(),
  updatedAt: timestamp('updated_at').defaultNow(),
  deletedAt: timestamp('deleted_at'),
});

export const hostelBedAllocations = pgTable('hostel_bed_allocations', {
  id: uuid('id').primaryKey().defaultRandom(),
  tenantId: uuid('tenant_id').notNull(),
  branchId: uuid('branch_id').notNull(),
  roomId: uuid('room_id').notNull(),
  studentId: uuid('student_id').notNull(),
  bedNumber: varchar('bed_number', { length: 20 }),
  allocationDate: date('allocation_date').notNull(),
  vacateDate: date('vacate_date'),
  status: varchar('status', { length: 20 }).default('active'),
  remarks: text('remarks'),
  createdAt: timestamp('created_at').defaultNow(),
  updatedAt: timestamp('updated_at').defaultNow(),
  deletedAt: timestamp('deleted_at'),
});

export const hostelAttendance = pgTable('hostel_attendance', {
  id: uuid('id').primaryKey().defaultRandom(),
  tenantId: uuid('tenant_id').notNull(),
  branchId: uuid('branch_id').notNull(),
  hostelId: uuid('hostel_id').notNull(),
  studentId: uuid('student_id').notNull(),
  date: date('date').notNull(),
  checkIn: timestamp('check_in'),
  checkOut: timestamp('check_out'),
  status: varchar('status', { length: 20 }).default('present'),
  remarks: text('remarks'),
  createdAt: timestamp('created_at').defaultNow(),
});

export const hostelVisitors = pgTable('hostel_visitors', {
  id: uuid('id').primaryKey().defaultRandom(),
  tenantId: uuid('tenant_id').notNull(),
  branchId: uuid('branch_id').notNull(),
  studentId: uuid('student_id').notNull(),
  visitorName: varchar('visitor_name', { length: 255 }).notNull(),
  relationship: varchar('relationship', { length: 100 }),
  phone: varchar('phone', { length: 20 }),
  visitDate: date('visit_date').notNull(),
  checkInTime: timestamp('check_in_time'),
  checkOutTime: timestamp('check_out_time'),
  purpose: text('purpose'),
  idProof: varchar('id_proof', { length: 100 }),
  idNumber: varchar('id_number', { length: 100 }),
  createdAt: timestamp('created_at').defaultNow(),
});

export const hostelDiscipline = pgTable('hostel_discipline', {
  id: uuid('id').primaryKey().defaultRandom(),
  tenantId: uuid('tenant_id').notNull(),
  branchId: uuid('branch_id').notNull(),
  studentId: uuid('student_id').notNull(),
  incidentDate: date('incident_date').notNull(),
  incidentType: varchar('incident_type', { length: 100 }).notNull(),
  description: text('description'),
  actionTaken: text('action_taken'),
  reportedBy: uuid('reported_by'),
  status: varchar('status', { length: 20 }).default('resolved'),
  createdAt: timestamp('created_at').defaultNow(),
  updatedAt: timestamp('updated_at').defaultNow(),
});
